version: '3'

services:

  mongocontainer:
    image: mongo:3.6.8
    ports:
    - 27017:27017
    command: --smallfiles

  mongo-init:
    build: ./mongo-init
    depends_on:
    - mongocontainer

  appcontainer:
    image: kmandalas/spring-mongodb-graphlookup
    ports:
    - 8080:8080
    depends_on:
    - mongocontainer