version: '3'

services:

  mongo1:
    image: mongo:4.4.1
    ports:
    - 27017:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongo-init/data-import/nodes.json:/tmp/nodes.json
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    networks:
    - net-spring-db

  mongo2:
    image: mongo:4.4.1
    ports:
    - 27018:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    networks:
    - net-spring-db

  mongo3:
    image: mongo:4.4.1
    ports:
    - 27019:27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
    networks:
    - net-spring-db

  mongo-init:
    build: ./mongo-init
    depends_on:
    - mongo1
    - mongo2
    - mongo3
    networks:
    - net-spring-db

networks:
  net-spring-db:
    driver: bridge